### PR TITLE
Return received internal transfers

### PR DESCRIPTION
**Pull request by pienkowb**

### CODE REVIEW

**Review by pawelnguyen — APPROVED** [review]

**Comment by pawelnguyen** [comment]
@lukanus can you take a look and let's deploy? ;)
https://www.notion.so/figmentnetworks/Celo-transactions-request-timeouts-12856ec67b7840cd9024380e16d28054

**Comment by lukanus** [comment]
Seems like I was too late @pawelnguyen  :) . was this deployed @pienkowb or do I need to do that?

**Comment by pienkowb** [comment]
@lukanus Not deployed yet, here's the release: https://github.com/figment-networks/celo-indexer/releases/tag/v0.3.5

**Comment by lukanus** [comment]
Let me release it then :)

czw., 18 lis 2021 o 13:39 Bartosz Pieńkowski ***@***.***>
napisał(a):

**Pull request merged**
